### ISSUE TITLE
Unable to arm alarm from Home Assistant

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#23] opened 2018-08-15 21:57 UTC
Using the web interface, I'm unable to arm the alarm away. The logs seem to also indicate no change. Can I provide any other detailed logging?

```
2018-08-15 14:41:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=alarm_control_panel, service=alarm_arm_away, service_data=entity_id=alarm_control_panel.elkm1_area_001, code=1234>
2018-08-15 14:41:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]>
2018-08-15 14:41:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event elkm1_sensor_event[L]: type=keypad, area=1, number=2, name=Front Door Keypd, attribute=last_user, user_at=1534369286.383535, user_num=(0,), user_name=User-203>
2018-08-15 14:41:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.elkm1_keypad_002, old_state=<state sensor.elkm1_keypad_002=unknown; Area=1, Last User Name=Jim Shank, Last User Number=1, Last User At=1534369017.3570416, unit_of_measurement=°F, friendly_name=Front Door Keypd, icon=mdi:thermometer-lines, hidden=True @ 2018-08-15T14:36:04.400538-07:00>, new_state=<state sensor.elkm1_keypad_002=unknown; Area=1, Last User Name=User-203, Last User Number=None, Last User At=1534369286.383535, unit_of_measurement=°F, friendly_name=Front Door Keypd, icon=mdi:thermometer-lines, hidden=True @ 2018-08-15T14:36:04.400538-07:00>>
2018-08-15 14:41:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=alarm_control_panel.elkm1_area_001, old_state=<state alarm_control_panel.elkm1_area_001=disarmed; code_format=[0-9]{4}([0-9]{2})?, changed_by=None, hidden=False, Last Armed At=0, Last Disarmed At=0, Last User Number=(1,), Last User At=1534369017.3570416, Last User Name=Jim Shank, Last Keypad Number=2, Last Keypad Name=Front Door Keypd, Readiness=Ready to arm, Arm Status=('Disarmed',), Alarm=('No alarm active',), friendly_name=Home @ 2018-08-15T14:36:01.062635-07:00>, new_state=<state alarm_control_panel.elkm1_area_001=disarmed; code_format=[0-9]{4}([0-9]{2})?, changed_by=None, hidden=False, Last Armed At=0, Last Disarmed At=0, Last User Number=(0,), Last User At=1534369286.383535, Last User Name=User-203, Last Keypad Number=2, Last Keypad Name=Front Door Keypd, Readiness=Ready to arm, Arm Status=('Disarmed',), Alarm=('No alarm active',), friendly_name=Home @ 2018-08-15T14:36:01.062635-07:00>>
```

**Comment by BioSehnsucht** [comment] 2018-08-16 03:21
Which commit are you using / how long ago did you install / update the integration? (not saying you should upgrade if it's not current commit, necessarily)

**Comment by jshank** [comment] 2018-08-16 14:35
Sorry, I usually note that at the header. 

ha-elkm1 version: bc57683e638059efaa1b487663d771e09283fa16
elkm1 library (gwww) 0.4.7
Home Assistant 0.75.2 (official docker container)
Elk M1 Version 05030A
Elk M1XEP Version 05030A

**Comment by BioSehnsucht** [comment] 2018-08-17 07:42
Worked in HASS 0.68.1 (what my docker was still on). Updated to latest docker (0.75.3) and arming seems to still work for both home and away.

Make sure you don't have ElkRP connected somewhere? That breaks pretty much any changes made by HASS to Elk.

If ElkRP isn't running, can you still toggle outputs or make any other changes from HASS to Elk?

**Comment by jshank** [comment] 2018-08-17 14:31
ElkRP is also connected to my ISY994i. Confirming that ElkRP can't support multiple connections?

**Comment by BioSehnsucht** [comment] 2018-08-17 16:14
Any time ElkRP is connected, the M1XEP (and also true for C1M1 I assume but I haven't directly tested it w/ C1M1) will block any messages originated from regular clients (i.e. our HASS integration). Outgoing notifications such as output change status updates will still be sent by the Elk, but we can't arm anything, toggle anything, and if we're just starting up we can't gather any information (i.e. names of devices, what actually is hooked up or not, etc). 

If you look at the extra attributes on the sensor.elkm1_panel_001 you'll find one for whether ElkRP is connected (Elk tells us ElkRP is connected and when it disconnects). If 'ElkRP' is 'Connected', then we actually discard all messages to the panel otherwise we just get back *more* messages from the panel telling us ElkRP is connected instead of the expected responses.

I should probably note this in the README... perhaps a mini-FAQ of common gotchas.

As for the ISY994i Elk module, it should have the same limitation - based on some googling it looks like ISY has the same issue with ElkRP : https://forum.universal-devices.com/topic/9328-isy-99-and-elk-m1-problem/ .

**Comment by jshank** [comment] 2018-08-17 16:21
Sorry, I misstated. ElkRP (the software) is not connected. I have an ISY994i also connected to the M1EXP. Would multiple clients to the M1EXP be causing the issue?

I checked back through the last few days of logs and at no time did it indicate "ElkRP=Connected"

**Comment by BioSehnsucht** [comment] 2018-08-18 06:34
No, that should be fine. There's probably some limit but I haven't run into it myself. I've had at least 3 clients connected without issues myself when testing. It must be another issue then. 

Do the other commands like toggling outputs, triggering tasks, or disarming the alarm work?

**Comment by jshank** [comment] 2018-08-18 19:39
It just got weirder. User 001 (me) is the only code that doesn't work for arming the alarm via HA. Naturally, I was using my own code for testing. I had the "Master" user authorization but I tested adding it to another working code and it made no difference.

**Comment by BioSehnsucht** [comment] 2018-08-19 09:13
What are the permissions (arm/disarm/master/... and which areas) for the non-working and working users?

**Comment by jshank** [comment] 2018-08-19 18:23
Thank you, your request to document the permissions led me to the solution. It may still be a bug or feature request, depending on how you look at it. 

User 001 is the only user on my system that has the `Access` User Authorization. As soon as I disabled that flag, I was able to arm and disarm the system with HA. Reading through the ELK M1 Gold programming guide, it states:

> A Yes allows this code to activate the Access Keypad Events 1313-1328 for the keypad where code is entered. Use the Whenever/And/Then Rules from Elk-RP to assign an output to this event for tripping a door strike or lock. 

> Note: If this code is enabled for arming, it will be necessary to press the Exit or Stay key to arm after the code.

Further searches indicate that the `Access` flag is used to [enable keycard automations.](https://www.elkproducts.com/door_entry_control.html)

Is this something that could be handled in the code, e.g. determine if the user has the access flag and then generate the exit or stay event?

**Comment by BioSehnsucht** [comment] 2018-08-19 20:26
For physical keypad usage, we can potentially determine that access only and not arming/disarming has occurred because we receive an access message but not a following arming/disarming immediately after. 

I'm not sure if the same is true if we're trying to arm, if we will receive an access message and thus try something else. As far as I can tell we always have to send an access code with the arming command ... so in theory if you just tried to arm twice the second try should work if this was going to work. It might not be possible to arm using a code that has access property, I'll have to test. Though I think if it was going to work simply trying to arm twice in HASS should do it...

Currently at my office we're using RFID cards with Elk and everyone has just access permissions. We're not yet using it for an alarm just access control, so we've only had the default arm/disarm USER 1 code set up, so I never ran into this issue. I do test that HASS can arm/disarm when making changes that may affect that portion of the integration but I've never tried it with an account that had Access set. We plan to use separate normal user codes for the few of us that will have arming permissions to arm the system (rather than using the RFID badges for arming).

But at least now we know what's happening so we can either work around it or document the limitation!

**Comment by jshank** [comment] 2018-08-21 15:33
Do you want to add anything more here or am I okay to close?

**Comment by BioSehnsucht** [comment] 2018-08-22 06:35
I guess we can close it, the root cause was identified and solved.

**Closed as completed by BioSehnsucht** 2018-08-22 06:35 UTC
